/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaarufIndexRouteImport } from './routes/taaruf/index'
import { Route as TaarufCategorySlugRouteImport } from './routes/taaruf/$categorySlug'
import { Route as TaarufApiRandomRouteImport } from './routes/taaruf/api.random'
import { Route as TaarufApiCategoriesRouteImport } from './routes/taaruf/api.categories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaarufIndexRoute = TaarufIndexRouteImport.update({
  id: '/taaruf/',
  path: '/taaruf/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaarufCategorySlugRoute = TaarufCategorySlugRouteImport.update({
  id: '/taaruf/$categorySlug',
  path: '/taaruf/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TaarufApiRandomRoute = TaarufApiRandomRouteImport.update({
  id: '/taaruf/api/random',
  path: '/taaruf/api/random',
  getParentRoute: () => rootRouteImport,
} as any)
const TaarufApiCategoriesRoute = TaarufApiCategoriesRouteImport.update({
  id: '/taaruf/api/categories',
  path: '/taaruf/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/taaruf/$categorySlug': typeof TaarufCategorySlugRoute
  '/taaruf/': typeof TaarufIndexRoute
  '/taaruf/api/categories': typeof TaarufApiCategoriesRoute
  '/taaruf/api/random': typeof TaarufApiRandomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/taaruf/$categorySlug': typeof TaarufCategorySlugRoute
  '/taaruf': typeof TaarufIndexRoute
  '/taaruf/api/categories': typeof TaarufApiCategoriesRoute
  '/taaruf/api/random': typeof TaarufApiRandomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/taaruf/$categorySlug': typeof TaarufCategorySlugRoute
  '/taaruf/': typeof TaarufIndexRoute
  '/taaruf/api/categories': typeof TaarufApiCategoriesRoute
  '/taaruf/api/random': typeof TaarufApiRandomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/taaruf/$categorySlug'
    | '/taaruf/'
    | '/taaruf/api/categories'
    | '/taaruf/api/random'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/taaruf/$categorySlug'
    | '/taaruf'
    | '/taaruf/api/categories'
    | '/taaruf/api/random'
  id:
    | '__root__'
    | '/'
    | '/taaruf/$categorySlug'
    | '/taaruf/'
    | '/taaruf/api/categories'
    | '/taaruf/api/random'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaarufCategorySlugRoute: typeof TaarufCategorySlugRoute
  TaarufIndexRoute: typeof TaarufIndexRoute
  TaarufApiCategoriesRoute: typeof TaarufApiCategoriesRoute
  TaarufApiRandomRoute: typeof TaarufApiRandomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taaruf/': {
      id: '/taaruf/'
      path: '/taaruf'
      fullPath: '/taaruf/'
      preLoaderRoute: typeof TaarufIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taaruf/$categorySlug': {
      id: '/taaruf/$categorySlug'
      path: '/taaruf/$categorySlug'
      fullPath: '/taaruf/$categorySlug'
      preLoaderRoute: typeof TaarufCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taaruf/api/random': {
      id: '/taaruf/api/random'
      path: '/taaruf/api/random'
      fullPath: '/taaruf/api/random'
      preLoaderRoute: typeof TaarufApiRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taaruf/api/categories': {
      id: '/taaruf/api/categories'
      path: '/taaruf/api/categories'
      fullPath: '/taaruf/api/categories'
      preLoaderRoute: typeof TaarufApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaarufCategorySlugRoute: TaarufCategorySlugRoute,
  TaarufIndexRoute: TaarufIndexRoute,
  TaarufApiCategoriesRoute: TaarufApiCategoriesRoute,
  TaarufApiRandomRoute: TaarufApiRandomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
